#!/bin/sh 
# \
exec tclsh "$0" "$@"

set input [read stdin]

proc filter {str} {
	 regsub -all { *\n   (.[^ ]|[^ ].)} $str { \1} result

	 return $result
}

puts [exec << [filter $input] sed \
		  -e {/g++-v3.*warning/d} \
		  -e {/g++-v3.*At global/d} \
		  -e {/g++-v3.*In instantiation/,/instantiated from here/d} \
		  -e {/g++-v3.*constructor/,/instantiated from here/d} \
		  -e {/g++-v3.*In function/,/instantiated from here/d} \
		  -e {/g++-v3.*In member/,/instantiated from here/d} \
		  -e {/operator.=.*should return by value/d} \
		  -e {/has a non-virtual destructor/d} \
		  ]
