#!/bin/csh -f

# $Id$

# An explanation of the sed operations:
#  1) remove all dependencies starting with '/usr'
#  2) remove all dependencies starting with '/opt'
#  3) remove all lines that now have no dependencies (since the system 
#     headers were removed)
#  4) make the dependency pertain to not just the *.o file, but also
#     the *.do file (debug object file) and the *.d file (the dependency file)
#

makedepend -f- -w500 $* | \
    sed -e 's@ /usr[^ ]*@@g' \
        -e 's@ /opt[^ ]*@@g' \
        -e 's@ [^ ]*/g++-3/[^ ]*@@g' \
        -e 's@ [^ ]*/gcc-lib/[^ ]*@@g' \
        -e '/^.*: *$/d' \
        -e 's@\.\.o@.o@g' \
        -e "s@^src/\(.*\)\.o:@dep/\1.d obj/$ARCH/\1.do obj/$ARCH/\1.o:@"

